/*
 * This source file was generated by the Gradle 'init' task
 */


import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

class Person {
    public Person(String name, String surname) {
        this.name = name;
        this.surname = surname;
    }

    String name;
    String surname;

}

public class App {
    public static void main(String[] args) {


        Gson myGson = new GsonBuilder().setPrettyPrinting().create();
        Person me = new Person("Ruslan", "Lomaka");
        String myNameGson = myGson.toJson(me);
        System.out.println("ME IS: "+myNameGson);
    }


}

